### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hiyak423** [hiyak423/furima-39575#20]
## フリマアプリのURL 
https://furima-39575.onrender.com/

## Basic認証ID、パスワード
adimin
0423

## 出品者用のメールアドレス、パスワード
furima1@imail.com
furima1

## 購入者用のメールアドレス、パスワード
furima2@imail.com
furima2

**Comment by motomuun** [comment]
@hiyak423 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品購入機能の確認**

- [ ] **クレジットカード情報は必須であり、PAY.JPテストカードの情報で決済ができること**
クレジットカード情報を入力するフォームに数値を入力することが出来ません。入力できるように修正をお願いします。

※購入後の機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by hiyak423** [comment]
@motomuun　さん、ご確認いただきありがとうございます。
修正箇所ですが、テストと本番環境で入力フォームの動作確認はできましたが、修正は行っていません。
リロードしないとjavadcriptが動作しなかったこともあり、読込時にturboを無効化しています。
技術的な面でわからないことは、14時からメンターさんに質問すればよろしいでしょうか？

**Comment by shodai-ito** [comment]
@hiyak423 さん、ご質問ありがとうございます！
turboを無効化されたとのことですので、こちらでも動作確認をいたしました。
購入ページに遷移した際は問題なくカード情報の入力ができましたが、一度購入に失敗するとそれ以降、カード情報の入力ができない状態となっておりました。

技術面の質問に関しましては、おっしゃる通り14時以降にメンターの方へご質問いただきますようお願いします。
特に本番環境のJavaScriptは、全体のコードを拝見するだけでは把握しかねる部分もあるため、ご理解いただけますと幸いです。

**Comment by hiyak423** [comment]
@shodai-ito  さん、ご確認いただきありがとうございます。
メンターさんに確認前ですが、下記の不具合を解消しました。ご確認をお願いいたします。
「 購入に失敗するとそれ以降、カード情報の入力ができない状態 」

**Comment by shodai-ito** [comment]
@hiyak423 さん、再度ご提出ありがとうございます。
ご自身で解決されたのは素晴らしいですね！

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました！
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます！
最終課題「FURIMA」の開発、お疲れ様でした。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
